name: kybank
description: "A new Flutter project."

publish_to: ''

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  flutter_screenutil: ^5.9.3
  form_builder_validators: ^11.0.0
  go_router: ^14.2.7
  lottie: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/ # This will include all images in the assets/images directory
    - assets/icon/
    - assets/lottie/
